### ISSUE TITLE
Missing efilib.h

### ISSUE THREAD

**Issue by tpimh** [yoppeh/efi#1]
I tried compiling some sample EFI code using your headers and most of the examples tried to include `efilib.h`. Would be nice to include it, so it can be a drop-in replacement.

**Comment by yoppeh** [comment]
This isn't really meant as a drop-in replacement for Tianocore or GNU EFI. I pretty much just put these headers together to use for custom programs that use the efi-clang repo and it's not expected to work with EFI code out there in the wild.  If you look at the README.md, you'll see the third sentence: "These are incomplete and you should probably use the official headers from Tianocore." 

Now, if you're writing something from scratch and you don't care about compatibility with Tianocore or GNU, then using these headers is a bit simpler: you aren't restricted to using the directory structure Tianocore imposes on you and you aren't linking in a ton of junk that GNU gives you. The sacrifice for that is having to deal with a non-standard structure.
