### ISSUE TITLE
Is it possible to port it on aarch64?

### ISSUE THREAD

**Issue by basedjakfan2** [yoppeh/efi#4]
Hello, I want to use this library in my project and I'm targeting aarch64 platform. In description it specifies it can work only on x86_64, how can I port it on desired Isa? What parts I should look for?

**Comment by yoppeh** [comment]
Look at this: 
https://krinkinmu.github.io/2020/11/21/EFI-aarch64.html
It gives info on compiling EFI code on an ARM system.
